# FOR TEST PURPOSES ONLY!

. "$(dirname "$0")/Config/env.sh"  # Sets $TRAVIS_SCRIPTS and $CURRENT_DIR, among others
. "$TRAVIS_SCRIPTS/Config/config.cfg"

echo "HOME: $HOME"
echo "TRAVIS_SCRIPTS: $TRAVIS_SCRIPTS"
echo "CURRENT_DIR: $CURRENT_DIR"
echo "REPOSITORY_NAME: $REPOSITORY_NAME"
echo "PROJECT_NAME: $PROJECT_NAME"
echo "PROJECT_PATH: $PROJECT_PATH"

echo "USE_CACHE: $USE_CACHE"
echo "GITHUB_NOTIFICATIONS: $GITHUB_NOTIFICATIONS"
echo "GITHUB_ISSUE_ID: $GITHUB_ISSUE_ID"
echo "SKIP_TESTS: $SKIP_TESTS"
echo "COMPILED_NAME: $COMPILED_NAME"
